### ISSUE TITLE
First benchmark always fails when running on .NET Core with -c release

### ISSUE THREAD

**Issue by cesarbs** [dotnet/BenchmarkDotNet#322]
Repro project here: https://github.com/cesarbs/BenchmarkFail

Steps to reproduce:

- Start from a clean repo
- `dotnet restore`
- `cd src/BenchmarkFail`
- `dotnet run -c release`

Output for the first benchmark:

```
// **************************
// Benchmark: Benchmarks.First: DefaultJob
// *** Generate ***
// Result = Success
// BinariesDirectoryPath = C:\Users\cesars\Documents\Visual Studio 2015\Projects\BenchmarkFail\BDN.Generated\binaries

// *** Build ***
C:\Program Files\dotnet\dotnet.exe compile-csc @C:\Users\cesars\Documents\Visual Studio 2015\Projects\BenchmarkFail\src\BenchmarkFail\obj\Release\netcoreapp1.1\dotnet-compile.rsp returned Exit Code 1
C:\Users\cesars\Documents\Visual Studio 2015\Projects\BenchmarkFail\src\BenchmarkFail\error CS2012: Cannot open 'C:\Users\cesars\Documents\Visual Studio 2015\Projects\BenchmarkFail\src\BenchmarkFail\bin\Release\netcoreapp1.1\BenchmarkFail.dll' for writing -- 'The process cannot access the file 'C:\Users\cesars\Documents\Visual Studio 2015\Projects\BenchmarkFail\src\BenchmarkFail\bin\Release\netcoreapp1.1\BenchmarkFail.dll' because it is being used by another process.'
// Result = Failure
```

**Does not happen when run with `-c Release` (note the uppercase R)**, but if you try that after running with `-c release` and not cleaning the repo, it fails in the same way.

Note the project containing the benchmarks **references another project as source**. This is required to repro.

Issue observed when running on Windows.

**Comment by halter73** [comment]
I think this is probably a misunderstanding and not a bug, so I'm adding on a comment to this issue. 

@cesarbs and I started adding `-c Release` to `dotnet run` because we were seeing warning like `Benchmark was built in DEBUG configuration. Please, build it in RELEASE.` after upgrading from 0.10.0 to 0.10.1.

The thing is, this doesn't seem necessary. I added the following to the benchmark project and it's dependencies and I saw "Running Release" in the benchmark output.

```
#if RELEASE
    Console.WriteLine("Running Release");
#else
    Console.WriteLine("Running Debug");
#endif
```

I also saw the following complaints about the assemblies being non-optimized, but when I looked at the assembly metadata in ILSpy, I see the DebuggingModes are `01 00 02 00 00 00 00 00` which according to [this StackOverflow answer](http://stackoverflow.com/a/5316565/719967) means it's optimized.

```
Assembly Microsoft.AspNetCore.Server.Kestrel.Performance, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 which defines benchmarks references non-optimized Microsoft.AspNetCore.Server.Kestrel
Assembly Microsoft.AspNetCore.Server.Kestrel.Performance, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 which defines benchmarks is non-optimized
```

```
.custom instance void [System.Runtime]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [System.Runtime]System.Diagnostics.DebuggableAttribute/DebuggingModes) = (
	01 00 02 00 00 00 00 00
)
```

**Comment by AndreyAkinshin** [comment]
@cesarbs, @halter73, thanks for the report.
@adamsitnik, could you take a look?

**Comment by adamsitnik** [comment]
Hello @cesarbs, @halter73!

Thanks for the bug report!

What we do today:
* analysis of the currently loaded dlls (all build in debug when executing simple `dotnet run`)
* warn the user about lack of the optimizations
* anyway we use `dotnet build -c Release` to build the auto generated project, which anyway with help of dotnet cli will rebuild all used projects in the Release mode.

So user did not run in Release but anyway we do that. I know it's not good, once I get back from holidays I fix it (after 26th of December).

Best regards,
Adam

**Comment by cesarbs** [comment]
@adamsitnik Thanks for the clarification! That still doesn't address the original issue though (that `dotnet run -c Release` works but `dotnet run -c release` doesn't). That should be case insensitive.

**Comment by adamsitnik** [comment]
@cesarbs the issue get resolved when we switched to the new csproj. My gut feeling tells me that it was more a dotnet cli bug than ours ;)
