### ISSUE TITLE
Give users nice warning when T in generic benchmark is not public

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/BenchmarkDotNet#741]
We now print an ugly error, instead of that the users should get a nice warning from a validator.

Repro:

```cs
public class Bench<T>  where T : new()
{
    [Benchmark] T New() => new T();
}

private class NotPublic { }

BenchmarkRunner.Run<Bench<NotPublic>>():
```

```
04740317-cbb6-4b4f-8ea5-770120ef36c5.notcs(1220,50): error CS0122: 'Request' is inaccessible due to its protection level [C:\Projects\corefxlab\tests\Benchmarks\bin\Release\netcoreapp2.1\04740317-cbb6-4b4f-8ea5-770120ef36c5\BenchmarkDotNet.Autogenerated.csproj]
04740317-cbb6-4b4f-8ea5-770120ef36c5.notcs(655,50): error CS0122: 'Request' is inaccessible due to its protection level [C:\Projects\corefxlab\tests\Benchmarks\bin\Release\netcoreapp2.1\04740317-cbb6-4b4f-8ea5-770120ef36c5\BenchmarkDotNet.Autogenerated.csproj]
04740317-cbb6-4b4f-8ea5-770120ef36c5.notcs(90,50): error CS0122: 'Request' is inaccessible due to its protection level [C:\Projects\corefxlab\tests\Benchmarks\bin\Release\netcoreapp2.1\04740317-cbb6-4b4f-8ea5-770120ef36c5\BenchmarkDotNet.Autogenerated.csproj]
    0 Warning(s)
    3 Error(s)
```

**Comment by Rizzen** [comment]
Solution introduced in https://github.com/dotnet/BenchmarkDotNet/pull/744
